# Site settings
title: Jacob Zylema's Personal Site
email: your-email@domain.com
description: "This is Jacob Zylema's personal site. Occasional ramblings; stories of failures and successes in various projects; a resume."
baseurl: ""
url: "http://jacobzylema.com"

# Build settings
markdown: kramdown
permalink: pretty
